// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase project configuration for DiaTrack
// Project: areraibhiunjosnnljvz
const SUPABASE_URL = "https://areraibhiunjosnnljvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyZXJhaWJoaXVuam9zbm5sanZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDUyMTgsImV4cCI6MjA3MDMyMTIxOH0.pQBQIJ8F_z1Vf97sHK4YhcQo3EW2tn_725JqiSkN14k";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});